Repository Activiti/activiti-cloud-process-model-service, pull requests merged in 2018-11, with the labels that each got.

#55 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#56 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#58 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#57 update org.activiti.cloud.modeling.build:activiti-cloud-modeling-parent to 7.0.3
  pom.xml
Labels: in progress, updatebot

#59 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#60 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#62 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#61 fix: add activiti-cloud-modeling-dependencies-tests module
  .mergify.yml
  .updatebot.yml
  activiti-cloud-process-model-dependencies/pom.xml
  activiti-cloud-services-process-model/pom.xml
  activiti-cloud-starter-process-model/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#63 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#64 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#65 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#67 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#66 remove bean overriding
  activiti-cloud-starter-process-model/src/test/resources/application.properties
Labels: in progress

#68 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#69 fix(versions): update Activiti/activiti-cloud-process-model-service versions
  pom.xml
Labels: in progress, updatebot

#70 missed this one
  activiti-cloud-services-process-model/activiti-cloud-services-process-model-rest/src/test/resources/application.properties
Labels: in progress
